---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alquran-cloud-api-memcached
  namespace: alquran-cloud
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: alquran-cloud-api-memcached
  template:
    metadata:
      labels:
        app: alquran-cloud-api-memcached
    spec:
      containers:
        - name: alquran-cloud-api-memcached
          image: memcached:1.5
          args:
            - '-m 64'
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 64Mi
          ports:
            - containerPort: 11211
              protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alquran-cloud-api-metrics
  namespace: monitoring
  labels:
    release: lke-monitor
spec:
  selector:
    matchLabels:
      name: alquran-cloud-api-metrics
  namespaceSelector:
    any: true
  endpoints:
    - port: "metrics"
      interval: 30s
---
#  Service
apiVersion: v1
kind: Service
metadata:
  name: alquran-cloud-api
  namespace: alquran-cloud
  annotations:
    konghq.com/plugins: rate-limiting-alquran-api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: alquran-cloud-api
---
apiVersion: v1
kind: Service
metadata:
  name: alquran-cloud-api-memcached
  namespace: alquran-cloud
spec:
  ports:
    - port: 11211
      targetPort: 11211
  selector:
    app: alquran-cloud-api-memcached
---
apiVersion: v1
kind: Service
metadata:
  name: alquran-cloud-api-metrics
  namespace: alquran-cloud
  labels:
    name: alquran-cloud-api-metrics
spec:
  type: ClusterIP
  selector:
    app: alquran-cloud-api
  ports:
    - name: metrics
      port: 9117
      targetPort: 9117
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-alquran-api
  namespace: alquran-cloud
config:
  second: 5 # 2 Ingress Pods. 60 requests per minute per IP - so 4 requests per IP per second, effectively.
  policy: local
plugin: rate-limiting
# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alquran-cloud-api
  namespace: alquran-cloud
spec:
  replicas: 3 # 16 requests each
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: alquran-cloud-api
  template:
    metadata:
      labels:
        app: alquran-cloud-api
    spec:
      containers:
        - name: apache-exporter-sidecar
          image: lusotycoon/apache-exporter
          args:
            - '--scrape_uri=http://localhost:8080/server-status?auto'
          ports:
            - containerPort: 9117
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: alquran-cloud-api
          image: islamicnetwork/api.alquran.cloud:$COMMIT_TAG
          env:
            - name:  MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: alquran-cloud-api-database
                  key: username
            - name:  MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alquran-cloud-api-database
                  key: password
            - name:  MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: alquran-cloud-api-database
                  key: database
            - name:  MYSQL_HOST_1
              value: "db.london.local.islamic.network"
            - name:  MYSQL_PORT_1
              value: "3306"
            - name:  MYSQL_HOST_2
              value: "db.london.local.islamic.network"
            - name:  MYSQL_PORT_2
              value: "3306"
            - name:  MYSQL_HOST_3
              value: "db.london.local.islamic.network"
            - name:  MYSQL_PORT_3
              value: "3306"
            - name:  MEMCACHED_HOST
              value: "alquran-cloud-api-memcached"
            - name:  MEMCACHED_PORT
              value: "11211"
          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: 8080
            initialDelaySeconds: 7
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /v1/status
              port: 8080
            periodSeconds: 7
            failureThreshold: 3
          resources:
            requests:
              cpu: "150m"
              memory: 250Mi
            limits:
              cpu: "250m"
              memory: 500Mi
          ports:
            - containerPort: 8080
              protocol: TCP
---
# HPA
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: alquran-cloud-api
  namespace: alquran-cloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alquran-cloud-api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alquran-cloud-api-ingress
  namespace: alquran-cloud
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: kong
spec:
  tls:
  - hosts:
    - "api.alquran.cloud"
    - "london.api.alquran.cloud"
    secretName: "alquran-cloud-api-tls"
  rules:
  - host: api.alquran.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: alquran-cloud-api
              port: 
                number: 80
  - host: london.api.alquran.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: alquran-cloud-api
              port: 
                number: 80
