---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: alquran-cloud-api
  namespace: alquran-cloud
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alquran-cloud-api
  updatePolicy:
    updateMode: "Off"  
