version: '3'
services:
  #######################################
  # PHP application Docker container
  #######################################
  alquran-app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
    - alquran-db
    depends_on:
    - alquran-db
    environment:
      MYSQL_USER: quran
      MYSQL_PASSWORD: quran
      MYSQL_DATABASE: quran
      MYSQL_HOST_1: quran-db
      MEMCACHED_HOST: quran-memcached
      MEMCACHED_PORT: 11211
      WAF_PROXY_MODE: 0
    ports:
    - "7070:8080"
    volumes:
    - .:/var/www
    privileged: true
    container_name: quran-app


  #######################################
  # MySQL server
  #######################################
  alquran-db:
    image: islamicnetwork/api.alquran.cloud-db:latest
      #    build:
      #context: .
      #dockerfile: Dockerfile.db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: quran
      MYSQL_PASSWORD: quran
      MYSQL_DATABASE: quran
      MYSQL_ROOT_PASSWORD: "root"
      #MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
    - "3306:3306"
    container_name: quran-db

  #######################################
  # PHPMyAdmin
  #######################################
  alquran-pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: quran-db
    ports:
    - "7071:80"
    links:
    - alquran-db
    depends_on:
    - alquran-db
    container_name: quran-pma

#######################################
  # Memcached
  #######################################
  alquran-memcached:
    image: memcached:1.5
    ports:
    - "11211:11211"
    container_name: quran-memcached

  #######################################
  # Memcached Admin
  #######################################
  alquran-memadmin:
    image: islamicnetwork/phpmemadmin:latest
    ports:
    - "7072:8080"
    environment:
      MEMADMIN_USERNAME: quran
      MEMADMIN_PASSWORD: quran
      MEMCACHED_HOST: quran-memcached
      MEMCACHED_PORT: 11211
    container_name: quran-memadmin
