version: '3'
services:
  alquran_api:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - memcached
      - mysql
    depends_on:
      - memcached
      - mysql
    environment:
      # DEBUG: "true" # Any value will make it true. For false, remove the variable.
      DB_USER: "api"
      DB_PASSWORD: "api"
      DB_NAME: "api"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      MEMCACHED_HOST: "memcached"
      MEMCACHED_PORT: 11211
    ports:
      - "80:8080"
    volumes:
      - .:/var/www
    privileged: true
    container_name: alquran_api

  alquran_api_mysql:
    image: islamicnetwork/api.alquran.cloud-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "api"
      MYSQL_DATABASE: "api"
    container_name: alquran_api_mysql
    ports:
      - "3306:3306"

#  couchdb:
#    image: couchdb:3.2
#    environment:
#      COUCHDB_USER: "api"
#      COUCHDB_PASSWORD: "api"
#    ports:
#      - "5984:5984"
#    container_name: couchdb

  alquran_api_memcached:
    image: memcached:1.6
    command:
      - "memcached"
      - "-m"
      - "64"
    container_name: alquran_api_memcached

