version: "3"
services:
  alquran_api:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - alquran_api_memcached
      - alquran_api_mysql
    depends_on:
      - alquran_api_memcached
      - alquran_api_mysql
    env_file:
      - alquran_api.env
    ports:
      - "80:8080"
    volumes:
      - .:/var/www
    privileged: true
    container_name: alquran_api

  alquran_api_mysql:
    image: islamicnetwork/api.alquran.cloud-db:latest
    env_file:
      - alquran_api.env
    container_name: alquran_api_mysql
    ports:
      - "3306:3306"

  #  couchdb:
  #    image: couchdb:3.2
  #    environment:
  #      COUCHDB_USER: "api"
  #      COUCHDB_PASSWORD: "api"
  #    ports:
  #      - "5984:5984"
  #    container_name: couchdb

  alquran_api_memcached:
    image: memcached:1.6
    command:
      - "memcached"
      - "-m"
      - "64"
    container_name: alquran_api_memcached
